#include <PipeFrame/Audio/AudioService.h>
#include <PipeFrame/Render/RenderServices2D.h>
#include <PipeFrame/Resources/AssetRegistry.h>
#include <cassert>
#include <string>
namespace {struct TextTag{};
void TestResources(){pipeframe::AssetRegistry<TextTag,std::string> registry;int loads=0;auto handle=registry.Load("asset",[&](std::string&){++loads;return std::optional<std::string>("ready");});assert(handle&&*registry.Get(handle)=="ready"&&loads==1);auto cached=registry.Load("asset",[&](std::string&){++loads;return std::optional<std::string>("wrong");});assert(cached==handle&&loads==1);assert(registry.MarkLost(handle,"device reset")&&registry.Info(handle)->state==pipeframe::ResourceState::Lost&&!registry.Get(handle));assert(registry.Reload(handle,[&](std::string&){return std::optional<std::string>("reloaded");})&&*registry.Get(handle)=="reloaded");assert(!registry.Reload(handle,[](std::string &error){error="missing";return std::optional<std::string>{};})&&registry.Info(handle)->error=="missing");pipeframe::TextureAtlas atlas;atlas.Set("ant",{{3,1},0,0,.5f,.5f});assert(atlas.Find("ant")&&atlas.Find("ant")->texture.index==3);}
void TestRendering(){pipeframe::VertexBatch2D batch(pipeframe::PrimitiveTopology::Triangles);batch.Add({{1,2},{3,4,5,6},{7,8}});auto command=batch.Command({9,1});assert(command.vertices.size()==1&&command.textureHandle==9);pipeframe::Path2D path{{{0,0},{1,1}}, {255,0,0,255},1,true};assert(pipeframe::BuildPathCommand(path).vertices.size()==3);pipeframe::SurfaceRegistry surfaces;pipeframe::PingPongSurface ping;ping.Initialize(surfaces,{64,64});const auto front=ping.Front();ping.Swap();assert(front==ping.Back()&&ping.Front()!=ping.Back());pipeframe::EffectGraph effects;effects.Add({pipeframe::EffectKind::BlurHorizontal});assert(effects.ResolvedKind(effects.Passes()[0],false)==pipeframe::EffectKind::Copy);pipeframe::ParticleSystem2D particles;particles.Emit({{0,0},{1,0},{255,255,255,255},1,.1f});particles.Update(.2f);assert(particles.Size()==0);pipeframe::DebugDraw2D debug;debug.Line({0,0},{1,1},{255,255,255,255});assert(debug.Command().vertices.size()==2);}
void TestAudioFailure(){pipeframe::AudioService audio;std::string error;auto handle=audio.LoadClip("/path/that/does/not/exist.wav",&error);auto cached=audio.LoadClip("/path/that/does/not/exist.wav");assert(handle&&cached==handle&&audio.State(handle)==pipeframe::ResourceState::Failed&&!error.empty()&&!audio.Play(handle));}
}
int main(){TestResources();TestRendering();TestAudioFailure();}
