// Generated by PipeFrame. Edit component/behaviour headers instead.
#pragma once
#include "Entities/Probe.h"
#include "Components/ProbeSettings.h"
#include "Behaviours/ProbeBehaviour.h"
namespace pipeframe_generated {
template<class Runtime> void Register(Runtime &runtime) {
    runtime.template RegisterEntity<Probe>({"project.Probe", "Probe", {}, {pipeframe::Transform2DComponentTypeId}});
    runtime.template RegisterComponent<ProbeSettings>();
    runtime.template RegisterBehaviour<ProbeBehaviour>("project.ProbeBehaviour", "ProbeBehaviour");
    (void)runtime;
}
}
